import type { Species } from '../../data/species';

// Fauna da Mata Atlântica. Status IUCN: tucano-de-bico-verde e saíra-sete-cores conferidos (LC, fichas de áreas-chave
// de biodiversidade); os demais vêm de memória (listas de 2024/2025) e estão marcados com "IUCN a confirmar".
// Habitats: floresta-umida (floresta de encosta), araucaria (mata de araucárias, no sul), mangue (manguezal, restinga e estuário).

export const SPECIES: Species[] = [
  {
    id: 'micoleao',
    name: 'Mico-leão-dourado',
    scientific: 'Leontopithecus rosalia',
    biome: 'mata-atlantica',
    size: 'pequeno',
    habitat: ['floresta-umida'],
    rarity: 'rara',
    iucn: 'EN', // IUCN a confirmar
    behavior: 'pula',
    colors: ['#F08A24', '#8A3220', '#FFC858', '#3E262C'],
    fact: 'Símbolo da Mata Atlântica, quase sumiu nos anos 1970. Hoje volta à mata graças a criações e corredores de floresta.',
  },
  {
    id: 'muriqui',
    name: 'Muriqui-do-sul',
    scientific: 'Brachyteles arachnoides',
    biome: 'mata-atlantica',
    size: 'grande',
    habitat: ['floresta-umida', 'araucaria'],
    rarity: 'lendaria',
    iucn: 'CR', // IUCN a confirmar
    behavior: 'calmo',
    colors: ['#B8A27A', '#4A3E36', '#E2D2AC', '#6A5648'],
    fact: 'O maior macaco das Américas é pacífico: não briga, abraça. Pendura-se pela cauda e come folhas lá no alto da copa.',
  },
  {
    id: 'tucanoverde',
    name: 'Tucano-de-bico-verde',
    scientific: 'Ramphastos dicolorus',
    biome: 'mata-atlantica',
    size: 'medio',
    habitat: ['floresta-umida', 'araucaria'],
    rarity: 'incomum',
    iucn: 'LC',
    behavior: 'pula',
    colors: ['#2A2430', '#8CB83A', '#F4D03A', '#D8322B'],
    fact: 'Come frutos e planta as sementes mata afora. O bico leve e oco ajuda a alcançar frutos nas pontas dos galhos.',
  },
  {
    id: 'saira',
    name: 'Saíra-sete-cores',
    scientific: 'Tangara seledon',
    biome: 'mata-atlantica',
    size: 'pequeno',
    habitat: ['floresta-umida', 'mangue'],
    rarity: 'comum',
    iucn: 'LC',
    behavior: 'voa',
    colors: ['#3AA8D8', '#2E8B57', '#F2B628', '#D8502B'],
    fact: 'Parece uma pequena paleta voadora: verde, azul, turquesa, laranja e preto numa ave de 13 cm. Vive em bandos que comem frutinhas.',
  },
  {
    id: 'jacutinga',
    name: 'Jacutinga',
    scientific: 'Aburria jacutinga',
    biome: 'mata-atlantica',
    size: 'medio',
    habitat: ['floresta-umida'],
    rarity: 'incomum',
    iucn: 'EN', // IUCN a confirmar
    behavior: 'calmo',
    colors: ['#2A2830', '#F2F0EA', '#3A6ED8', '#D8322B'],
    fact: 'Engole frutos do palmito-juçara e espalha as sementes. Com a caça do palmito e das próprias aves, ficou raríssima.',
  },
  {
    id: 'pingodeouro',
    name: 'Sapinho-pingo-de-ouro',
    scientific: 'Brachycephalus ephippium',
    biome: 'mata-atlantica',
    size: 'pequeno',
    habitat: ['floresta-umida'],
    rarity: 'incomum',
    iucn: 'LC', // IUCN a confirmar
    behavior: 'pula',
    colors: ['#F4A818', '#C8501E', '#FFE070', '#6A3A1E'],
    fact: 'Do tamanho de uma moeda, vive na serrapilheira. A cor de ouro avisa que a pele é tóxica, e ele nem precisa pular longe.',
  },
  {
    id: 'jararaca',
    name: 'Jararaca',
    scientific: 'Bothrops jararaca',
    biome: 'mata-atlantica',
    size: 'medio',
    habitat: ['floresta-umida', 'mangue'],
    rarity: 'comum',
    iucn: 'LC', // IUCN a confirmar
    behavior: 'bote',
    colors: ['#8A7A4A', '#3E2E22', '#D8C890', '#5A4A32'],
    fact: 'Camufla-se na folhagem seca e espera a presa passar. Do seu veneno nasceu um remédio para pressão alta.',
  },
  {
    id: 'ourico',
    name: 'Ouriço-cacheiro',
    scientific: 'Coendou spinosus',
    biome: 'mata-atlantica',
    size: 'medio',
    habitat: ['floresta-umida', 'araucaria'],
    rarity: 'incomum',
    iucn: 'LC', // IUCN a confirmar
    behavior: 'casco',
    colors: ['#5A4636', '#E8D8A8', '#2A2022', '#A8805A'],
    fact: 'Sai à noite e sobe nas árvores usando a cauda como uma quinta mão. Os espinhos não são lançados, mas soltam fácil.',
  },
  {
    id: 'caranguejo',
    name: 'Caranguejo-uçá',
    scientific: 'Ucides cordatus',
    biome: 'mata-atlantica',
    size: 'pequeno',
    habitat: ['mangue'],
    rarity: 'comum',
    iucn: 'LC', // IUCN a confirmar
    behavior: 'bote',
    colors: ['#4A7AB8', '#2A3E6A', '#E87A3A', '#8A6A4A'],
    fact: 'Habitante da lama do manguezal, cava tocas fundas e come folhas caídas. Na época da andada, os machos saem em bando.',
  },
  {
    id: 'botocinza',
    name: 'Boto-cinza',
    scientific: 'Sotalia guianensis',
    biome: 'mata-atlantica',
    size: 'grande',
    habitat: ['mangue'],
    rarity: 'rara',
    iucn: 'NT', // IUCN a confirmar
    behavior: 'mergulha',
    colors: ['#7C8EA0', '#4A5A6E', '#C8D4DC', '#E8A0A8'],
    fact: 'Vive em baías e estuários, perto da costa. Pula da água e pesca em grupo, tocando uns aos outros enquanto nadam.',
  },
  {
    id: 'cararoxa',
    name: 'Papagaio-de-cara-roxa',
    scientific: 'Amazona brasiliensis',
    biome: 'mata-atlantica',
    size: 'medio',
    habitat: ['mangue', 'araucaria'],
    rarity: 'rara',
    iucn: 'NT', // IUCN a confirmar
    behavior: 'voa',
    colors: ['#3EA84A', '#8A4A9A', '#D8322B', '#2A6A3A'],
    fact: 'Dorme nas ilhas e no mangue e voa ao amanhecer para comer frutos no continente. É um dos papagaios mais raros do litoral.',
  },
  {
    id: 'gralhaazul',
    name: 'Gralha-azul',
    scientific: 'Cyanocorax caeruleus',
    biome: 'mata-atlantica',
    size: 'medio',
    habitat: ['araucaria', 'floresta-umida'],
    rarity: 'comum',
    iucn: 'NT', // IUCN a confirmar
    behavior: 'voa',
    colors: ['#2A3ECC', '#141A44', '#6A8AF0', '#E8E4F0'],
    fact: 'Esconde pinhões no chão e esquece boa parte: é a grande plantadora de araucárias. Ave símbolo do Paraná.',
  },
];
