import type { Species } from '../../data/species';

// Fauna do Cerrado. Status IUCN de memória (listas de 2024/2025); confirme em iucnredlist.org antes de publicar.
// Habitats: campo (campo limpo e sujo), cerradao (cerradão, árvores tortas), vereda (buritizal, brejo e córrego).

export const SPECIES: Species[] = [
  {
    id: 'loboguara',
    name: 'Lobo-guará',
    scientific: 'Chrysocyon brachyurus',
    biome: 'cerrado',
    size: 'grande',
    habitat: ['campo', 'cerradao'],
    rarity: 'rara',
    iucn: 'NT',
    behavior: 'pula',
    colors: ['#C8742E', '#1E1A1A', '#F2E6CC', '#8A4A22'],
    fact: 'O maior canídeo da América do Sul, de pernas longas para enxergar sobre o capim. Adora a lobeira, fruta que é metade de sua dieta.',
  },
  {
    id: 'tamandua',
    name: 'Tamanduá-bandeira',
    scientific: 'Myrmecophaga tridactyla',
    biome: 'cerrado',
    size: 'grande',
    habitat: ['campo'],
    rarity: 'rara',
    iucn: 'VU',
    behavior: 'calmo',
    colors: ['#7A7068', '#1E1A1C', '#EDE6D8', '#4A423E'],
    fact: 'Não tem dentes: lambe até 30 mil cupins e formigas por dia com uma língua de 60 cm. Dorme coberto pela cauda peluda.',
  },
  {
    id: 'tatucanastra',
    name: 'Tatu-canastra',
    scientific: 'Priodontes maximus',
    biome: 'cerrado',
    size: 'grande',
    habitat: ['cerradao', 'campo'],
    rarity: 'rara',
    iucn: 'VU',
    behavior: 'casco',
    colors: ['#5E5048', '#2A2224', '#E8DCC0', '#8E7C6C'],
    fact: 'O maior tatu do mundo, com a maior garra entre os animais vivos. Suas tocas abrigam outros bichos depois que ele vai embora.',
  },
  {
    id: 'seriema',
    name: 'Seriema',
    scientific: 'Cariama cristata',
    biome: 'cerrado',
    size: 'medio',
    habitat: ['campo'],
    rarity: 'comum',
    iucn: 'LC',
    behavior: 'bote',
    colors: ['#A89A86', '#4A3E36', '#F2ECE0', '#D8463A'],
    fact: 'Ave de pernas longas que prefere correr a voar. Bate cobras contra o chão para matá-las e canta alto ao amanhecer.',
  },
  {
    id: 'ema',
    name: 'Ema',
    scientific: 'Rhea americana',
    biome: 'cerrado',
    size: 'grande',
    habitat: ['campo'],
    rarity: 'comum',
    iucn: 'NT',
    behavior: 'calmo',
    colors: ['#9A8C7C', '#4E4438', '#E6DCCA', '#6E6256'],
    fact: 'A maior ave do Brasil não voa, mas corre a 60 km/h. É o macho que choca os ovos de várias fêmeas e cuida dos filhotes.',
  },
  {
    id: 'canide',
    name: 'Arara-canindé',
    scientific: 'Ara ararauna',
    biome: 'cerrado',
    size: 'medio',
    habitat: ['vereda', 'cerradao'],
    rarity: 'incomum',
    iucn: 'LC',
    behavior: 'voa',
    colors: ['#2E7ED6', '#F2C21E', '#F4F0E4', '#1E3E7A'],
    fact: 'Faz o ninho em buracos de buritis mortos. Forma casais para a vida toda e voa sempre em pares.',
  },
  {
    id: 'tucano',
    name: 'Tucano-toco',
    scientific: 'Ramphastos toco',
    biome: 'cerrado',
    size: 'medio',
    habitat: ['cerradao'],
    rarity: 'comum',
    iucn: 'LC',
    behavior: 'pula',
    colors: ['#1E1C22', '#F27A1E', '#F6F2EA', '#3A7ACA'],
    fact: 'Seu bico enorme é leve e oco, e ajuda a perder calor. Salta de galho em galho e engole frutos jogando a cabeça para trás.',
  },
  {
    id: 'patomergulhao',
    name: 'Pato-mergulhão',
    scientific: 'Mergus octosetaceus',
    biome: 'cerrado',
    size: 'medio',
    habitat: ['vereda'],
    rarity: 'lendaria',
    iucn: 'CR',
    behavior: 'mergulha',
    colors: ['#2E3A38', '#8A4A2E', '#E4E0D4', '#C8402E'],
    fact: 'Um dos patos mais ameaçados do mundo: só vive em rios de água limpa e correnteza, por isso é um termômetro da saúde da água. Mergulha para pescar.',
  },
  {
    id: 'raposinha',
    name: 'Raposinha-do-campo',
    scientific: 'Lycalopex vetulus',
    biome: 'cerrado',
    size: 'medio',
    habitat: ['campo'],
    rarity: 'incomum',
    iucn: 'LC',
    behavior: 'pula',
    colors: ['#A89A8C', '#2A2428', '#EAC48E', '#6E625A'],
    fact: 'Raposa pequena endêmica do Brasil, de boca pequena para comer cupins e besouros. Caça de noite e vive em tocas no campo.',
  },
  {
    id: 'jiboia',
    name: 'Jiboia',
    scientific: 'Boa constrictor',
    biome: 'cerrado',
    size: 'medio',
    habitat: ['cerradao'],
    rarity: 'incomum',
    iucn: 'LC',
    behavior: 'bote',
    colors: ['#9A7A52', '#4A2E22', '#D8C08A', '#A8452E'],
    fact: 'Não tem veneno: mata a presa apertando-a. A cauda avermelhada é sua marca, e os filhotes nascem prontos para caçar.',
  },
  {
    id: 'buraqueira',
    name: 'Coruja-buraqueira',
    scientific: 'Athene cunicularia',
    biome: 'cerrado',
    size: 'pequeno',
    habitat: ['campo'],
    rarity: 'comum',
    iucn: 'LC',
    behavior: 'voa',
    colors: ['#A8865E', '#5A4430', '#F4EEDE', '#E8C84A'],
    fact: 'Coruja que vive no chão e caça de dia, em tocas abandonadas de tatus. Faz uma "reverência" quando fica desconfiada.',
  },
  {
    id: 'vagalume',
    name: 'Vaga-lume-do-cupinzeiro',
    scientific: 'Pyrearinus termitilluminans',
    biome: 'cerrado',
    size: 'pequeno',
    habitat: ['campo', 'cerradao'],
    rarity: 'incomum',
    iucn: 'NE',
    behavior: 'calmo',
    colors: ['#3E3A2E', '#7AE86A', '#C8F29A', '#8A6A3E'],
    fact: 'As larvas acendem uma luz verde nos cupinzeiros, de noite, e atraem insetos para comer. Os campos do Cerrado brilham no início das chuvas.',
  },
];
