import type { Species } from '../../data/species';

// Fauna do Pantanal. Status IUCN de memória/fontes secundárias; confirme em iucnredlist.org antes de publicar.
// Habitats: alagado (campos alagados, margens, água rasa), baia (baías e rios), cordilheira (ilhas de mata).

export const SPECIES: Species[] = [
  {
    id: 'jacare',
    name: 'Jacaré-do-pantanal',
    scientific: 'Caiman yacare',
    biome: 'pantanal',
    size: 'grande',
    habitat: ['alagado', 'baia'],
    rarity: 'comum',
    iucn: 'LC',
    behavior: 'bote',
    colors: ['#6B7A3E', '#2E3A22', '#D8CF9A', '#E3B33A'],
    fact: 'Há milhões deles no Pantanal, o que o torna o maior bando de crocodilianos do planeta. Na seca, se amontoam nas poças que sobram.',
  },
  {
    id: 'capivara',
    name: 'Capivara',
    scientific: 'Hydrochoerus hydrochaeris',
    biome: 'pantanal',
    size: 'grande',
    habitat: ['alagado', 'cordilheira'],
    rarity: 'comum',
    iucn: 'LC',
    behavior: 'calmo',
    colors: ['#9A6E44', '#5A3E2A', '#CFA878', '#2E2018'],
    fact: 'Maior roedor do mundo. Olhos, orelhas e narinas ficam no alto da cabeça, para ela poder se esconder na água só com isso de fora.',
  },
  {
    id: 'tuiuiu',
    name: 'Tuiuiú',
    scientific: 'Jabiru mycteria',
    biome: 'pantanal',
    size: 'grande',
    habitat: ['alagado'],
    rarity: 'incomum',
    iucn: 'LC',
    behavior: 'voa',
    colors: ['#F4F2EC', '#1E1E24', '#D8322B', '#8E9096'],
    fact: 'Ave-símbolo do Pantanal, com mais de 1,4 m. O colar vermelho no pescoço aparece quando a pele se estica durante a corte.',
  },
  {
    id: 'araraazul',
    name: 'Arara-azul-grande',
    scientific: 'Anodorhynchus hyacinthinus',
    biome: 'pantanal',
    size: 'medio',
    habitat: ['cordilheira'],
    rarity: 'lendaria',
    iucn: 'VU',
    behavior: 'voa',
    colors: ['#2A4FC8', '#16288A', '#F2C82E', '#1E1E26'],
    fact: 'Maior papagaio do mundo, com cerca de 1 m. Quebra o coco de acuri com o bico e nidifica em ocos do manduvi.',
  },
  {
    id: 'cervo',
    name: 'Cervo-do-pantanal',
    scientific: 'Blastocerus dichotomus',
    biome: 'pantanal',
    size: 'grande',
    habitat: ['alagado'],
    rarity: 'rara',
    iucn: 'VU',
    behavior: 'pula',
    colors: ['#B8642E', '#3A2A22', '#F2E6D2', '#6E3A22'],
    fact: 'Maior cervídeo da América do Sul. As patas, de cor escura, têm dedos que se abrem para não afundar no lodo.',
  },
  {
    id: 'piranha',
    name: 'Piranha-vermelha',
    scientific: 'Pygocentrus nattereri',
    biome: 'pantanal',
    size: 'pequeno',
    habitat: ['baia'],
    rarity: 'comum',
    iucn: 'LC',
    behavior: 'bote',
    colors: ['#8E9AA4', '#C8322B', '#2E3A44', '#E8A02E'],
    fact: 'Vive em cardumes e come de tudo, até carniça. Os dentes em lâmina cortam como tesoura, mas ataques a gente são raros.',
  },
  {
    id: 'anta',
    name: 'Anta',
    scientific: 'Tapirus terrestris',
    biome: 'pantanal',
    size: 'grande',
    habitat: ['cordilheira', 'alagado'],
    rarity: 'rara',
    iucn: 'VU',
    behavior: 'calmo',
    colors: ['#6E5A4C', '#3A2E28', '#B8A890', '#E8E2D2'],
    fact: 'Maior mamífero terrestre do Brasil. Usa a tromba curta para pegar folhas e como snorkel quando atravessa rios.',
  },
  {
    id: 'quati',
    name: 'Quati',
    scientific: 'Nasua nasua',
    biome: 'pantanal',
    size: 'medio',
    habitat: ['cordilheira'],
    rarity: 'comum',
    iucn: 'LC',
    behavior: 'pula',
    colors: ['#A8683A', '#2E2018', '#E8D8B8', '#6A4A2E'],
    fact: 'As fêmeas andam em bandos com os filhotes, de rabo erguido. O focinho comprido fuça a terra atrás de insetos.',
  },
  {
    id: 'colhereiro',
    name: 'Colhereiro',
    scientific: 'Platalea ajaja',
    biome: 'pantanal',
    size: 'medio',
    habitat: ['alagado'],
    rarity: 'incomum',
    iucn: 'LC',
    behavior: 'calmo',
    colors: ['#F2A0B8', '#D8325A', '#F8F2EE', '#8E8A6A'],
    fact: 'Varre a água rasa de um lado para o outro com o bico em forma de colher. O rosa vem dos crustáceos que come.',
  },
  {
    id: 'bugio',
    name: 'Bugio-preto',
    scientific: 'Alouatta caraya',
    biome: 'pantanal',
    size: 'medio',
    habitat: ['cordilheira'],
    rarity: 'incomum',
    iucn: 'NT', // IUCN a confirmar
    behavior: 'pula',
    colors: ['#2A2428', '#12101A', '#8A6E52', '#5A4A44'],
    fact: 'Seu urro, ouvido a quilômetros, marca o território do bando. Só os machos são pretos: as fêmeas são cor de palha.',
  },
  {
    id: 'dourado',
    name: 'Dourado',
    scientific: 'Salminus brasiliensis',
    biome: 'pantanal',
    size: 'medio',
    habitat: ['baia'],
    rarity: 'incomum',
    iucn: 'LC',
    behavior: 'pula',
    colors: ['#D89A2A', '#8A4A1E', '#F4D878', '#E0602A'],
    fact: 'O "rei do rio" salta fora da água e sobe a correnteza para desovar. Caça outros peixes na emboscada.',
  },
  {
    id: 'jaguatirica',
    name: 'Jaguatirica',
    scientific: 'Leopardus pardalis',
    biome: 'pantanal',
    size: 'medio',
    habitat: ['cordilheira'],
    rarity: 'rara',
    iucn: 'LC',
    behavior: 'bote',
    colors: ['#D6A860', '#2A1E1A', '#F4EAD6', '#8A5A2E'],
    fact: 'Felino noturno que caça roedores e aves do chão ao galho. Cada uma tem um desenho único de rosetas na pelagem.',
  },
];
